name: annotseba
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - snakemake>=7.0
  - ncbi-datasets-cli        # datasets / dataformat CLI
  - assembly-stats
  - quast>=5.2
  - busco>=5.4
  - typing_extensions>=4.6
  - agat
  - matplotlib
  - pandas
